openapi: 3.0.1
info:
  title: Auth API
  description: API para autenticación de usuarios.
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Autenticar usuario
      description: Genera un token de autenticación para el usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Token generado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Solicitud inválida.
        '500':
          description: Error interno del servidor.
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: Nombre de usuario.
        password:
          type: string
          description: Contraseña del usuario.
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: Token de autenticación generado.