openapi: 3.0.1
info:
  title: Auth API
  description: API para gestion de coachs.
  version: 1.0.0
paths:
  /user/coaches:
    post:
      summary: Create coach
      description: Create new coach
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoachCreationRequest'
      responses:
        '200':
          description: Coach created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoachCreationResponse'
        '400':
          description: Invalid Request.
        '500':
          description: Server error.
components:
  schemas:
    CoachCreationRequest:
      type: object
      required:
        - user
        - id
      properties:
        user:
          type: uuid
          description: User id
        id:
          type: coach
          description: Coach id
        name:
          type: string
          description: Name of the coach.
        location:
          type: string
          description: Location of the coach.
        languages:
          type: array
          items:
            type: string
          description: List of languages spoken by the coach.
        physical:
          type: boolean
          description: Offers physical training services.
        experienceYears:
          type: integer
          format: int32
        bio:
          type: string
          description: Coach biography.
        availability:
          type: array
          items:
            $ref: "./common.yml#/TimeSlot"
        clients:
          type: array
          items:
            type: uuid
          description: List of client ids associated with the coach.
        nutritionist:
          type: boolean
          description: Offers nutritionist services.
        trainer:
          type: boolean
          description: Offers trainer services.

    CoachCreationResponse:
      type: object
      properties:
        token:
          type: string
          description: Generated
