fitmentor:
  domain: c0b28b449254.ngrok-free.app

spring.application.name: fitmentor
spring:
  cache:
    type: caffeine
    cache-names: foods
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
      caches:
        foods:
          spec: maximumSize=500,expireAfterAccess=6000s
  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
      locations: classpath:db/migration
      enabled: true
  main:
      allow-bean-definition-overriding: true

jwt:
    secret: |
        random string dfsdfenrñjweugb
        must be a long string in order to 
        have more than 256 bytes, so I think that I should 
        write some more characters here: 
        lets see: 1, 2, 3
    issuer: "fitmentor"
    audience: "user"
    header: Authorization
    prefix: Bearer
    token-type: JWT