spring.application.name: fitmentor
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/base
        username: user
        password: pass
    jpa:
        hibernate:
        ddl-auto: update
        show-sql: true
    flyway:
        locations: classpath:db/migration
        enabled: true
    main:
        allow-bean-definition-overriding: true
server:
    port: 8080